In [7]:
import numpy as np
import time
import sys
size = 1000 # 1000000

l1 = range(size)
l2 = range(size)
a1 = np.arange(size)
a2 = np.arange(size)

start = time.time()
result= [(x+y) for x,y in zip(l1,l2)]
print ("print list time took :",(time.time()-start)*1000)

start = time.time()
result= a1+a2
print ("print numpy array time took:",(time.time()-start)*1000)

('print list time took :', 0.0)
('print numpy array time took:', 0.9999275207519531)


In [11]:
import numpy as np
a = np.array([2,3,4])
print a

[2 3 4]


NameError: name 'array' is not defined

In [12]:
array([2, 3, 4])
a.dtype

NameError: name 'array' is not defined

In [16]:
import numpy as np
a = np.array([2,3,4])
print a
print array([2, 3, 4])
a.dtype
dtype('int64')
b = np.array([1.2, 3.5, 5.1])
print b
b.dtype
dtype('float64')

[2 3 4]


NameError: name 'array' is not defined

In [17]:
np.zeros( (3,4) )

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [18]:
np.ones( (2,3,4), dtype=np.int16 )

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [19]:
np.empty( (2,3) )

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [20]:
from numpy import pi
print np.linspace( 0, 2, 9 ) # 9 numbers from 0 to 2

[ 0.    0.25  0.5   0.75  1.    1.25  1.5   1.75  2.  ]


In [21]:
x = np.linspace( 0, 2*pi, 100 ) # useful to evaluate function at lots of points
f = np.sin(x)
print f

[  0.00000000e+00   6.34239197e-02   1.26592454e-01   1.89251244e-01
   2.51147987e-01   3.12033446e-01   3.71662456e-01   4.29794912e-01
   4.86196736e-01   5.40640817e-01   5.92907929e-01   6.42787610e-01
   6.90079011e-01   7.34591709e-01   7.76146464e-01   8.14575952e-01
   8.49725430e-01   8.81453363e-01   9.09631995e-01   9.34147860e-01
   9.54902241e-01   9.71811568e-01   9.84807753e-01   9.93838464e-01
   9.98867339e-01   9.99874128e-01   9.96854776e-01   9.89821442e-01
   9.78802446e-01   9.63842159e-01   9.45000819e-01   9.22354294e-01
   8.95993774e-01   8.66025404e-01   8.32569855e-01   7.95761841e-01
   7.55749574e-01   7.12694171e-01   6.66769001e-01   6.18158986e-01
   5.67059864e-01   5.13677392e-01   4.58226522e-01   4.00930535e-01
   3.42020143e-01   2.81732557e-01   2.20310533e-01   1.58001396e-01
   9.50560433e-02   3.17279335e-02  -3.17279335e-02  -9.50560433e-02
  -1.58001396e-01  -2.20310533e-01  -2.81732557e-01  -3.42020143e-01
  -4.00930535e-01  -4.58226522e-01

In [23]:
a = np.arange(6) # 1d array
print(a)

[0 1 2 3 4 5]


In [22]:
b = np.arange(12).reshape(4,3) # 2d array
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [25]:
A = np.array( [[1,1],[0,1]] )
B = np.array( [[2,0],[3,4]] )
a*b

ValueError: operands could not be broadcast together with shapes (6,) (4,3) 